zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

---
spring:
  profiles: default
  eureka:
    instance:
      # enable to register multiple app instances with a random server port
      instance-id: ${spring.application.name}:${random.uuid}
      
---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411
  eureka:
    client:
      serviceUrl:
        defaultZone: http://discovery-server:8761/eureka/

---
spring:
  profiles: kubernetes
  zipkin:
    baseUrl: http://tracing-server:9411
  eureka:
    client:
      serviceUrl:
        defaultZone: http://discovery-server:8761/eureka/
    instance:
      preferIPAddress: true

---
spring:
  profiles: inspectit
  inspectit:
    exporters:
      metrics:
        prometheus:
          port: 9074
    service:
      name: spcm-api-gateway