server:
  port: 8081

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411
  eureka:
    client:
      serviceUrl:
        defaultZone: http://discovery-server:8761/eureka/

---
spring:
  profiles: kubernetes
  zipkin:
    baseUrl: http://tracing-server:9411
  eureka:
    client:
      serviceUrl:
        defaultZone: http://discovery-server:8761/eureka/
    instance:
      preferIPAddress: true

---
spring:
  profiles: inspectit
  inspectit:
    exporters:
      metrics:
        prometheus:
          port: 9071
    service:
      name: spcm-customers-service