vets:
  cache:
    ttl: 60
    heap-size: 100

server:
  port: 8083

---
spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

---
spring:
  profiles: kubernetes
  zipkin:
    baseUrl: http://tracing-server:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    preferIPAddress: true

---
spring:
  profiles: inspectit
inspectit:
  exporters:
    metrics:
      prometheus:
        port: 9073
  service:
    name: spcm-vets-service